// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xotdugorsjottntjgddx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdGR1Z29yc2pvdHRudGpnZGR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwODQwMTIsImV4cCI6MjA1NzY2MDAxMn0.gbsgLNlde6U5bSIkP920DisRe6qrhVpiFTDVAgc3JbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);